package com.coolgatty.palaria.mobs.models;

import org.lwjgl.opengl.GL11;

import com.coolgatty.palaria.mobs.EntityNimatin;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.boss.EntityDragon;
import net.minecraft.util.MathHelper;

public class ModelNimatin extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightfrontleg1;
    ModelRenderer rightfrontleg2;
    ModelRenderer rightfrontfoot;
    ModelRenderer rightfrontclaw1;
    ModelRenderer rightfrontclaw2;
    ModelRenderer rightfrontclaw3;
    ModelRenderer leftfrontleg1;
    ModelRenderer leftfrontleg2;
    ModelRenderer leftfrontfoot;
    ModelRenderer leftfrontclaw1;
    ModelRenderer leftfrontclaw2;
    ModelRenderer leftfrontclaw3;
    ModelRenderer rightbackleg1;
    ModelRenderer rightbackleg2;
    ModelRenderer rightbackleg3;
    ModelRenderer rightbackfoot;
    ModelRenderer rightbackclaw1;
    ModelRenderer rightbackclaw2;
    ModelRenderer rightbackclaw3;
    ModelRenderer leftbackleg1;
    ModelRenderer leftbackleg2;
    ModelRenderer leftbackleg3;
    ModelRenderer leftbackfoot;
    ModelRenderer leftbackclaw1;
    ModelRenderer leftbackclaw2;
    ModelRenderer leftbackclaw3;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer jaw;
    ModelRenderer nose;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer tooth3;
    ModelRenderer tooth4;
    
  public ModelNimatin()
  {
    textureWidth = 256;
    textureHeight = 256;
    if (this.isChild)
    {
    	head = new ModelRenderer(this, 0, 31);
        head.addBox(-8F, -5F, -9F, 16, 14, 16);
        head.setRotationPoint(-1F, 0F, -24F);
        head.setTextureSize(256, 256);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body = new ModelRenderer(this, 32, 68);
        body.addBox(0F, 0F, 0F, 14, 16, 45);
        body.setRotationPoint(-8F, -1F, -24F);
        body.setTextureSize(256, 256);
        body.mirror = true;
        setRotation(body, 0.0F, 0F, 0F);
        rightfrontleg1 = new ModelRenderer(this, 0, 61);
        rightfrontleg1.addBox(-4F, -2F, -4F, 7, 12, 7);
        rightfrontleg1.setRotationPoint(-9F, -1F, -12F);
        rightfrontleg1.setTextureSize(256, 256);
        rightfrontleg1.mirror = true;
        setRotation(rightfrontleg1, 0F, 0F, 0F);
        rightfrontleg2 = new ModelRenderer(this, 0, 80);
        rightfrontleg2.addBox(-3.9F, 6F, -2F, 7, 16, 6);
        rightfrontleg2.setRotationPoint(-9F, -1F, -12F);
        rightfrontleg2.setTextureSize(256, 256);
        rightfrontleg2.mirror = true;
        setRotation(rightfrontleg2, 0F, 0F, 0F);
        rightfrontfoot = new ModelRenderer(this, 0, 102);
        rightfrontfoot.addBox(-4F, 21F, -5F, 7, 3, 9);
        rightfrontfoot.setRotationPoint(-9F, 0F, -12F);
        rightfrontfoot.setTextureSize(256, 256);
        rightfrontfoot.mirror = true;
        setRotation(rightfrontfoot, 0F, 0F, 0F);
        rightfrontclaw1 = new ModelRenderer(this, 0, 114);
        rightfrontclaw1.addBox(1F, 23F, -7F, 1, 2, 3);
        rightfrontclaw1.setRotationPoint(-9F, -1F, -12F);
        rightfrontclaw1.setTextureSize(256, 256);
        rightfrontclaw1.mirror = true;
        setRotation(rightfrontclaw1, 0F, 0F, 0F);
        rightfrontclaw2 = new ModelRenderer(this, 0, 119);
        rightfrontclaw2.addBox(-1F, 23F, -8F, 1, 2, 4);
        rightfrontclaw2.setRotationPoint(-9F, -1F, -12F);
        rightfrontclaw2.setTextureSize(256, 256);
        rightfrontclaw2.mirror = true;
        setRotation(rightfrontclaw2, 0F, 0F, 0F);
        rightfrontclaw3 = new ModelRenderer(this, 0, 114);
        rightfrontclaw3.addBox(-3F, 23F, -7F, 1, 2, 3);
        rightfrontclaw3.setRotationPoint(-9F, -1F, -12F);
        rightfrontclaw3.setTextureSize(256, 256);
        rightfrontclaw3.mirror = true;
        setRotation(rightfrontclaw3, 0F, 0F, 0F);
        leftfrontleg1 = new ModelRenderer(this, 0, 61);
        leftfrontleg1.addBox(-4F, -2F, -4F, 7, 12, 7);
        leftfrontleg1.setRotationPoint(7F, -1F, -12F);
        leftfrontleg1.setTextureSize(256, 256);
        leftfrontleg1.mirror = true;
        setRotation(leftfrontleg1, 0F, 0F, 0F);
        leftfrontleg2 = new ModelRenderer(this, 0, 80);
        leftfrontleg2.addBox(-3.9F, 6F, -2F, 7, 16, 6);
        leftfrontleg2.setRotationPoint(7F, -1F, -12F);
        leftfrontleg2.setTextureSize(256, 256);
        leftfrontleg2.mirror = true;
        setRotation(leftfrontleg2, 0F, 0F, 0F);
        leftfrontfoot = new ModelRenderer(this, 0, 102);
        leftfrontfoot.addBox(-4F, 21F, -3F, 7, 3, 9);
        leftfrontfoot.setRotationPoint(7F, 0F, -14F);
        leftfrontfoot.setTextureSize(256, 256);
        leftfrontfoot.mirror = true;
        setRotation(leftfrontfoot, 0F, 0F, 0F);
        leftfrontclaw1 = new ModelRenderer(this, 0, 114);
        leftfrontclaw1.addBox(1F, 23F, -7F, 1, 2, 3);
        leftfrontclaw1.setRotationPoint(7F, -1F, -12F);
        leftfrontclaw1.setTextureSize(256, 256);
        leftfrontclaw1.mirror = true;
        setRotation(leftfrontclaw1, 0F, 0F, 0F);
        leftfrontclaw2 = new ModelRenderer(this, 0, 119);
        leftfrontclaw2.addBox(-1F, 23F, -8F, 1, 2, 4);
        leftfrontclaw2.setRotationPoint(7F, -1F, -12F);
        leftfrontclaw2.setTextureSize(256, 256);
        leftfrontclaw2.mirror = true;
        setRotation(leftfrontclaw2, 0F, 0F, 0F);
        leftfrontclaw3 = new ModelRenderer(this, 0, 114);
        leftfrontclaw3.addBox(-3F, 23F, -7F, 1, 2, 3);
        leftfrontclaw3.setRotationPoint(7F, -1F, -12F);
        leftfrontclaw3.setTextureSize(256, 256);
        leftfrontclaw3.mirror = true;
        setRotation(leftfrontclaw3, 0F, 0F, 0F);
        rightbackleg1 = new ModelRenderer(this, 28, 61);
        rightbackleg1.addBox(-4F, -2F, -2F, 7, 12, 8);
        rightbackleg1.setRotationPoint(-9F, -1F, 12F);
        rightbackleg1.setTextureSize(256, 256);
        rightbackleg1.mirror = true;
        setRotation(rightbackleg1, 0F, 0F, 0F);
        rightbackleg2 = new ModelRenderer(this, 30, 81);
        rightbackleg2.addBox(-3.9F, 6F, -1.5F, 7, 8, 7);
        rightbackleg2.setRotationPoint(-9F, -1F, 12F);
        rightbackleg2.setTextureSize(256, 256);
        rightbackleg2.mirror = true;
        setRotation(rightbackleg2, 0F, 0F, 0F);
        rightbackleg3 = new ModelRenderer(this, 32, 96);
        rightbackleg3.addBox(-4F, 13F, -1F, 7, 11, 6);
        rightbackleg3.setRotationPoint(-9F, -1F, 12F);
        rightbackleg3.setTextureSize(256, 256);
        rightbackleg3.mirror = true;
        setRotation(rightbackleg3, 0F, 0F, 0F);
        rightbackfoot = new ModelRenderer(this, 0, 102);
        rightbackfoot.addBox(-4F, 22F, -4F, 7, 3, 9);
        rightbackfoot.setRotationPoint(-9F, -1F, 12F);
        rightbackfoot.setTextureSize(256, 256);
        rightbackfoot.mirror = true;
        setRotation(rightbackfoot, 0F, 0F, 0F);
        rightbackclaw1 = new ModelRenderer(this, 0, 114);
        rightbackclaw1.addBox(-3F, 23F, -6F, 1, 2, 3);
        rightbackclaw1.setRotationPoint(-9F, -1F, 12F);
        rightbackclaw1.setTextureSize(256, 256);
        rightbackclaw1.mirror = true;
        setRotation(rightbackclaw1, 0F, 0F, 0F);
        rightbackclaw2 = new ModelRenderer(this, 0, 114);
        rightbackclaw2.addBox(1F, 23F, -6F, 1, 2, 3);
        rightbackclaw2.setRotationPoint(-9F, -1F, 12F);
        rightbackclaw2.setTextureSize(256, 256);
        rightbackclaw2.mirror = true;
        setRotation(rightbackclaw2, 0F, 0F, 0F);
        rightbackclaw3 = new ModelRenderer(this, 0, 119);
        rightbackclaw3.addBox(-1F, 23F, -7F, 1, 2, 4);
        rightbackclaw3.setRotationPoint(-9F, -1F, 12F);
        rightbackclaw3.setTextureSize(256, 256);
        rightbackclaw3.mirror = true;
        setRotation(rightbackclaw3, 0F, 0F, 0F);
        leftbackleg1 = new ModelRenderer(this, 28, 61);
        leftbackleg1.addBox(-4F, -2F, -2F, 7, 12, 8);
        leftbackleg1.setRotationPoint(7F, -1F, 12F);
        leftbackleg1.setTextureSize(256, 256);
        leftbackleg1.mirror = true;
        setRotation(leftbackleg1, 0F, 0F, 0F);
        leftbackleg2 = new ModelRenderer(this, 30, 81);
        leftbackleg2.addBox(-3.9F, 6F, -1.5F, 7, 8, 7);
        leftbackleg2.setRotationPoint(7F, -1F, 12F);
        leftbackleg2.setTextureSize(256, 256);
        leftbackleg2.mirror = true;
        setRotation(leftbackleg2, 0F, 0F, 0F);
        leftbackleg3 = new ModelRenderer(this, 32, 96);
        leftbackleg3.addBox(-4F, 13F, -1F, 7, 11, 6);
        leftbackleg3.setRotationPoint(7F, -1F, 12F);
        leftbackleg3.setTextureSize(256, 256);
        leftbackleg3.mirror = true;
        setRotation(leftbackleg3, 0F, 0F, 0F);
        leftbackfoot = new ModelRenderer(this, 0, 102);
        leftbackfoot.addBox(-4F, 22F, -4F, 7, 3, 9);
        leftbackfoot.setRotationPoint(7F, -1F, 12F);
        leftbackfoot.setTextureSize(256, 256);
        leftbackfoot.mirror = true;
        setRotation(leftbackfoot, 0F, 0F, 0F);
        leftbackclaw1 = new ModelRenderer(this, 0, 114);
        leftbackclaw1.addBox(-3F, 23F, -6F, 1, 2, 3);
        leftbackclaw1.setRotationPoint(7F, -1F, 12F);
        leftbackclaw1.setTextureSize(256, 256);
        leftbackclaw1.mirror = true;
        setRotation(leftbackclaw1, 0F, 0F, 0F);
        leftbackclaw2 = new ModelRenderer(this, 0, 114);
        leftbackclaw2.addBox(1F, 23F, -6F, 1, 2, 3);
        leftbackclaw2.setRotationPoint(7F, -1F, 12F);
        leftbackclaw2.setTextureSize(256, 256);
        leftbackclaw2.mirror = true;
        setRotation(leftbackclaw2, 0F, 0F, 0F);
        leftbackclaw3 = new ModelRenderer(this, 0, 119);
        leftbackclaw3.addBox(-1F, 23F, -7F, 1, 2, 4);
        leftbackclaw3.setRotationPoint(7F, -1F, 12F);
        leftbackclaw3.setTextureSize(256, 256);
        leftbackclaw3.mirror = true;
        setRotation(leftbackclaw3, 0F, 0F, 0F);
        tail1 = new ModelRenderer(this, 56, 53);
        tail1.addBox(-3F, 0F, 0F, 6, 6, 8);
        tail1.setRotationPoint(-1F, 0F, 21F);
        tail1.setTextureSize(256, 256);
        tail1.mirror = true;
        setRotation(tail1, -0.4363323F, 0F, 0F);
        tail2 = new ModelRenderer(this, 56, 53);
        tail2.addBox(-3F, 0F, 8F, 6, 6, 8);
        tail2.setRotationPoint(-1F, 0F, 21F);
        tail2.setTextureSize(256, 256);
        tail2.mirror = true;
        setRotation(tail2, -0.4363323F, 0F, 0F);
        tail3 = new ModelRenderer(this, 84, 54);
        tail3.addBox(-2.5F, 8F, 11F, 5, 5, 8);
        tail3.setRotationPoint(-1F, 0F, 21F);
        tail3.setTextureSize(256, 256);
        tail3.mirror = true;
        setRotation(tail3, 0.0872665F, 0F, 0F);
        tail4 = new ModelRenderer(this, 110, 53);
        tail4.addBox(-2.5F, 8F, 19F, 5, 5, 9);
        tail4.setRotationPoint(-1F, 0F, 21F);
        tail4.setTextureSize(256, 256);
        tail4.mirror = true;
        setRotation(tail4, 0.0872665F, 0F, 0F);
        tail5 = new ModelRenderer(this, 138, 53);
        tail5.addBox(-2.5F, 8F, 27F, 5, 5, 9);
        tail5.setRotationPoint(-1F, 0F, 21F);
        tail5.setTextureSize(256, 256);
        tail5.mirror = true;
        setRotation(tail5, 0.0872665F, 0F, 0F);
        jaw = new ModelRenderer(this, 51, 29);
        jaw.addBox(-6F, 7F, -21F, 12, 2, 16);
        jaw.setRotationPoint(-1F, 0F, -24F);
        jaw.setTextureSize(256, 256);
        jaw.mirror = true;
        setRotation(jaw, 0F, 0F, 0F);
        nose = new ModelRenderer(this, 50, 130);
        nose.addBox(-6F, 2F, -21F, 12, 5, 16);
        nose.setRotationPoint(-1F, 0F, -24F);
        nose.setTextureSize(256, 256);
        nose.mirror = true;
        setRotation(nose, 0F, 0F, 0F);
        tooth1 = new ModelRenderer(this, 15, 15);
        tooth1.addBox(-7F, 0F, -21F, 2, 6, 2);
        tooth1.setRotationPoint(-1F, 10F, -24F);
        tooth1.setTextureSize(256, 256);
        tooth1.mirror = true;
        setRotation(tooth1, 0F, 0F, 0F);
        tooth2 = new ModelRenderer(this, 15, 15);
        tooth2.addBox(5F, 0F, -21F, 2, 6, 2);
        tooth2.setRotationPoint(-1F, 10F, -24F);
        tooth2.setTextureSize(256, 256);
        tooth2.mirror = true;
        setRotation(tooth2, 0F, 0F, 0F);
        tooth3 = new ModelRenderer(this, 11, 20);
        tooth3.addBox(-5F, 5F, -20F, 1, 2, 1);
        tooth3.setRotationPoint(-1F, 0F, -24F);
        tooth3.setTextureSize(256, 256);
        tooth3.mirror = true;
        setRotation(tooth3, 0F, 0F, 0F);
        tooth4 = new ModelRenderer(this, 11, 20);
        tooth4.addBox(4F, 5F, -20F, 1, 2, 1);
        tooth4.setRotationPoint(-1F, 0F, -24F);
        tooth4.setTextureSize(256, 256);
        tooth4.mirror = true;
        setRotation(tooth4, 0F, 0F, 0F);
    }
    else
    {
      head = new ModelRenderer(this, 0, 31);
      head.addBox(-8F, -7F, -16F, 16, 14, 16);
      head.setRotationPoint(-1F, 0F, -24F);
      head.setTextureSize(256, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F); 
      body = new ModelRenderer(this, 32, 68);
      body.addBox(0F, 0F, 0F, 14, 16, 45);
      body.setRotationPoint(-8F, -1F, -24F);
      body.setTextureSize(256, 256);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightfrontleg1 = new ModelRenderer(this, 0, 61);
      rightfrontleg1.addBox(-4F, -2F, -4F, 7, 12, 7);
      rightfrontleg1.setRotationPoint(-9F, -1F, -12F);
      rightfrontleg1.setTextureSize(256, 256);
      rightfrontleg1.mirror = true;
      setRotation(rightfrontleg1, 0F, 0F, 0F);
      rightfrontleg2 = new ModelRenderer(this, 0, 80);
      rightfrontleg2.addBox(-3.9F, 6F, -2F, 7, 16, 6);
      rightfrontleg2.setRotationPoint(-9F, -1F, -12F);
      rightfrontleg2.setTextureSize(256, 256);
      rightfrontleg2.mirror = true;
      setRotation(rightfrontleg2, 0F, 0F, 0F);
      rightfrontfoot = new ModelRenderer(this, 0, 102);
      rightfrontfoot.addBox(-4F, 21F, -5F, 7, 3, 9);
      rightfrontfoot.setRotationPoint(-9F, 0F, -12F);
      rightfrontfoot.setTextureSize(256, 256);
      rightfrontfoot.mirror = true;
      setRotation(rightfrontfoot, 0F, 0F, 0F);
      rightfrontclaw1 = new ModelRenderer(this, 0, 114);
      rightfrontclaw1.addBox(1F, 23F, -7F, 1, 2, 3);
      rightfrontclaw1.setRotationPoint(-9F, -1F, -12F);
      rightfrontclaw1.setTextureSize(256, 256);
      rightfrontclaw1.mirror = true;
      setRotation(rightfrontclaw1, 0F, 0F, 0F);
      rightfrontclaw2 = new ModelRenderer(this, 0, 119);
      rightfrontclaw2.addBox(-1F, 23F, -8F, 1, 2, 4);
      rightfrontclaw2.setRotationPoint(-9F, -1F, -12F);
      rightfrontclaw2.setTextureSize(256, 256);
      rightfrontclaw2.mirror = true;
      setRotation(rightfrontclaw2, 0F, 0F, 0F);
      rightfrontclaw3 = new ModelRenderer(this, 0, 114);
      rightfrontclaw3.addBox(-3F, 23F, -7F, 1, 2, 3);
      rightfrontclaw3.setRotationPoint(-9F, -1F, -12F);
      rightfrontclaw3.setTextureSize(256, 256);
      rightfrontclaw3.mirror = true;
      setRotation(rightfrontclaw3, 0F, 0F, 0F);
      leftfrontleg1 = new ModelRenderer(this, 0, 61);
      leftfrontleg1.addBox(-4F, -2F, -7F, 7, 12, 7);
      leftfrontleg1.setRotationPoint(7F, -1F, -12F);
      leftfrontleg1.setTextureSize(256, 256);
      leftfrontleg1.mirror = true;
      setRotation(leftfrontleg1, 0F, 0F, 0F);
      leftfrontleg2 = new ModelRenderer(this, 0, 80);
      leftfrontleg2.addBox(-3.9F, 6F, -2F, 7, 16, 6);
      leftfrontleg2.setRotationPoint(7F, -1F, -12F);
      leftfrontleg2.setTextureSize(256, 256);
      leftfrontleg2.mirror = true;
      setRotation(leftfrontleg2, 0F, 0F, 0F);
      leftfrontfoot = new ModelRenderer(this, 0, 102);
      leftfrontfoot.addBox(-4F, 21F, -3F, 7, 3, 9);
      leftfrontfoot.setRotationPoint(7F, 0F, -14F);
      leftfrontfoot.setTextureSize(256, 256);
      leftfrontfoot.mirror = true;
      setRotation(leftfrontfoot, 0F, 0F, 0F);
      leftfrontclaw1 = new ModelRenderer(this, 0, 114);
      leftfrontclaw1.addBox(1F, 23F, -7F, 1, 2, 3);
      leftfrontclaw1.setRotationPoint(7F, -1F, -12F);
      leftfrontclaw1.setTextureSize(256, 256);
      leftfrontclaw1.mirror = true;
      setRotation(leftfrontclaw1, 0F, 0F, 0F);
      leftfrontclaw2 = new ModelRenderer(this, 0, 119);
      leftfrontclaw2.addBox(-1F, 23F, -8F, 1, 2, 4);
      leftfrontclaw2.setRotationPoint(7F, -1F, -12F);
      leftfrontclaw2.setTextureSize(256, 256);
      leftfrontclaw2.mirror = true;
      setRotation(leftfrontclaw2, 0F, 0F, 0F);
      leftfrontclaw3 = new ModelRenderer(this, 0, 114);
      leftfrontclaw3.addBox(-3F, 23F, -7F, 1, 2, 3);
      leftfrontclaw3.setRotationPoint(7F, -1F, -12F);
      leftfrontclaw3.setTextureSize(256, 256);
      leftfrontclaw3.mirror = true;
      setRotation(leftfrontclaw3, 0F, 0F, 0F);
      rightbackleg1 = new ModelRenderer(this, 28, 61);
      rightbackleg1.addBox(-4F, -2F, -2F, 7, 12, 8);
      rightbackleg1.setRotationPoint(-9F, -1F, 12F);
      rightbackleg1.setTextureSize(256, 256);
      rightbackleg1.mirror = true;
      setRotation(rightbackleg1, 0F, 0F, 0F);
      rightbackleg2 = new ModelRenderer(this, 30, 81);
      rightbackleg2.addBox(-3.9F, 6F, -1.5F, 7, 8, 7);
      rightbackleg2.setRotationPoint(-9F, -1F, 12F);
      rightbackleg2.setTextureSize(256, 256);
      rightbackleg2.mirror = true;
      setRotation(rightbackleg2, 0F, 0F, 0F);
      rightbackleg3 = new ModelRenderer(this, 32, 96);
      rightbackleg3.addBox(-4F, 13F, -1F, 7, 11, 6);
      rightbackleg3.setRotationPoint(-9F, -1F, 12F);
      rightbackleg3.setTextureSize(256, 256);
      rightbackleg3.mirror = true;
      setRotation(rightbackleg3, 0F, 0F, 0F);
      rightbackfoot = new ModelRenderer(this, 0, 102);
      rightbackfoot.addBox(-4F, 22F, -4F, 7, 3, 9);
      rightbackfoot.setRotationPoint(-9F, -1F, 12F);
      rightbackfoot.setTextureSize(256, 256);
      rightbackfoot.mirror = true;
      setRotation(rightbackfoot, 0F, 0F, 0F);
      rightbackclaw1 = new ModelRenderer(this, 0, 114);
      rightbackclaw1.addBox(-3F, 23F, -6F, 1, 2, 3);
      rightbackclaw1.setRotationPoint(-9F, -1F, 12F);
      rightbackclaw1.setTextureSize(256, 256);
      rightbackclaw1.mirror = true;
      setRotation(rightbackclaw1, 0F, 0F, 0F);
      rightbackclaw2 = new ModelRenderer(this, 0, 114);
      rightbackclaw2.addBox(1F, 23F, -6F, 1, 2, 3);
      rightbackclaw2.setRotationPoint(-9F, -1F, 12F);
      rightbackclaw2.setTextureSize(256, 256);
      rightbackclaw2.mirror = true;
      setRotation(rightbackclaw2, 0F, 0F, 0F);
      rightbackclaw3 = new ModelRenderer(this, 0, 119);
      rightbackclaw3.addBox(-1F, 23F, -7F, 1, 2, 4);
      rightbackclaw3.setRotationPoint(-9F, -1F, 12F);
      rightbackclaw3.setTextureSize(256, 256);
      rightbackclaw3.mirror = true;
      setRotation(rightbackclaw3, 0F, 0F, 0F);
      leftbackleg1 = new ModelRenderer(this, 28, 61);
      leftbackleg1.addBox(-4F, -2F, 0F, 7, 12, 8);
      leftbackleg1.setRotationPoint(7F, -1F, 12F);
      leftbackleg1.setTextureSize(256, 256);
      leftbackleg1.mirror = true;
      setRotation(leftbackleg1, 0F, 0F, 0F);
      leftbackleg2 = new ModelRenderer(this, 30, 81);
      leftbackleg2.addBox(-4F, 3F, -13F, 7, 8, 7);
      leftbackleg2.setRotationPoint(7F, -1F, 12F);
      leftbackleg2.setTextureSize(256, 256);
      leftbackleg2.mirror = true;
      setRotation(leftbackleg2, 0.6981317F, 0F, 0F);
      leftbackleg3 = new ModelRenderer(this, 32, 96);
      leftbackleg3.addBox(-4F, 13F, -1F, 7, 11, 6);
      leftbackleg3.setRotationPoint(7F, -1F, 12F);
      leftbackleg3.setTextureSize(256, 256);
      leftbackleg3.mirror = true;
      setRotation(leftbackleg3, -0.1745329F, 0F, 0F);
      leftbackfoot = new ModelRenderer(this, 0, 102);
      leftbackfoot.addBox(-4F, 22F, -8F, 7, 3, 9);
      leftbackfoot.setRotationPoint(7F, -1F, 12F);
      leftbackfoot.setTextureSize(256, 256);
      leftbackfoot.mirror = true;
      setRotation(leftbackfoot, 0F, 0F, 0F);
      leftbackclaw1 = new ModelRenderer(this, 0, 114);
      leftbackclaw1.addBox(-3F, 23F, -10F, 1, 2, 3);
      leftbackclaw1.setRotationPoint(7F, -1F, 12F);
      leftbackclaw1.setTextureSize(256, 256);
      leftbackclaw1.mirror = true;
      setRotation(leftbackclaw1, 0F, 0F, 0F);
      leftbackclaw2 = new ModelRenderer(this, 0, 114);
      leftbackclaw2.addBox(1F, 23F, -10F, 1, 2, 3);
      leftbackclaw2.setRotationPoint(7F, -1F, 12F);
      leftbackclaw2.setTextureSize(256, 256);
      leftbackclaw2.mirror = true;
      setRotation(leftbackclaw2, 0F, 0F, 0F);
      leftbackclaw3 = new ModelRenderer(this, 0, 119);
      leftbackclaw3.addBox(-1F, 23F, -11F, 1, 2, 4);
      leftbackclaw3.setRotationPoint(7F, -1F, 12F);
      leftbackclaw3.setTextureSize(256, 256);
      leftbackclaw3.mirror = true;
      setRotation(leftbackclaw3, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 56, 53);
      tail1.addBox(-3F, 0F, 0F, 6, 6, 8);
      tail1.setRotationPoint(-1F, 0F, 21F);
      tail1.setTextureSize(256, 256);
      tail1.mirror = true;
      setRotation(tail1, -0.4363323F, 0F, 0F);
      tail2 = new ModelRenderer(this, 56, 53);
      tail2.addBox(-3F, 0F, 8F, 6, 6, 8);
      tail2.setRotationPoint(-1F, 0F, 21F);
      tail2.setTextureSize(256, 256);
      tail2.mirror = true;
      setRotation(tail2, -0.4363323F, 0F, 0F);
      tail3 = new ModelRenderer(this, 84, 54);
      tail3.addBox(-2.5F, 8F, 11F, 5, 5, 8);
      tail3.setRotationPoint(-1F, 0F, 21F);
      tail3.setTextureSize(256, 256);
      tail3.mirror = true;
      setRotation(tail3, 0.0872665F, 0F, 0F);
      tail4 = new ModelRenderer(this, 110, 53);
      tail4.addBox(-2.5F, 8F, 19F, 5, 5, 9);
      tail4.setRotationPoint(-1F, 0F, 21F);
      tail4.setTextureSize(256, 256);
      tail4.mirror = true;
      setRotation(tail4, 0.0872665F, 0F, 0F);
      tail5 = new ModelRenderer(this, 138, 53);
      tail5.addBox(-2.5F, 8F, 27F, 5, 5, 9);
      tail5.setRotationPoint(-1F, 0F, 21F);
      tail5.setTextureSize(256, 256);
      tail5.mirror = true;
      setRotation(tail5, 0.0872665F, 0F, 0F);
      jaw = new ModelRenderer(this, 51, 29);
      jaw.addBox(-6F, 5F, -28F, 12, 2, 16);
      jaw.setRotationPoint(-1F, 0F, -24F);
      jaw.setTextureSize(256, 256);
      jaw.mirror = true;
      setRotation(jaw, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 50, 130);
      nose.addBox(-6F, 0F, -28F, 12, 5, 16);
      nose.setRotationPoint(-1F, 0F, -24F);
      nose.setTextureSize(256, 256);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      tooth1 = new ModelRenderer(this, 15, 15);
      tooth1.addBox(-7F, -5F, -28F, 2, 6, 2);
      tooth1.setRotationPoint(-1F, 0F, -24F);
      tooth1.setTextureSize(256, 256);
      tooth1.mirror = true;
      setRotation(tooth1, 0.3490659F, 0F, 0F);
      tooth2 = new ModelRenderer(this, 15, 15);
      tooth2.addBox(5F, -5F, -28F, 2, 6, 2);
      tooth2.setRotationPoint(-1F, 0F, -24F);
      tooth2.setTextureSize(256, 256);
      tooth2.mirror = true;
      setRotation(tooth2, 0.3490659F, 0F, 0F);
      tooth3 = new ModelRenderer(this, 11, 20);
      tooth3.addBox(-5F, 3F, -27F, 1, 2, 1);
      tooth3.setRotationPoint(-1F, 0F, -24F);
      tooth3.setTextureSize(256, 256);
      tooth3.mirror = true;
      setRotation(tooth3, 0F, 0F, 0F);
      tooth4 = new ModelRenderer(this, 11, 20);
      tooth4.addBox(4F, 3F, -27F, 1, 2, 1);
      tooth4.setRotationPoint(-1F, 0F, -24F);
      tooth4.setTextureSize(256, 256);
      tooth4.mirror = true;
      setRotation(tooth4, 0F, 0F, 0F);
    }
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    if (this.isChild)
    {
        float var8 = 2.0F;
        GL11.glPushMatrix();
        GL11.glScalef(1.5F / var8, 1.5F / var8, 1.5F / var8);
        GL11.glTranslatef(0.0F, 10.0F * par7, 4.0F * par7);
        head.render(par7);
        jaw.render(par7);
        nose.render(par7);
        tooth1.render(par7);
        tooth2.render(par7);
        tooth3.render(par7);
        tooth4.render(par7);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glScalef(1.0F / var8, 1.0F / var8, 1.0F / var8);
        GL11.glTranslatef(0.0F, 24.0F * par7, 0.0F);
        body.render(par7);
        rightfrontleg1.render(par7);
        rightfrontleg2.render(par7);
        rightfrontfoot.render(par7);
        rightfrontclaw1.render(par7);
        rightfrontclaw2.render(par7);
        rightfrontclaw3.render(par7);
        leftfrontleg1.render(par7);
        leftfrontleg2.render(par7);
        leftfrontfoot.render(par7);
        leftfrontclaw1.render(par7);
        leftfrontclaw2.render(par7);
        leftfrontclaw3.render(par7);
        rightbackleg1.render(par7);
        rightbackleg2.render(par7);
        rightbackleg3.render(par7);
        rightbackfoot.render(par7);
        rightbackclaw1.render(par7);
        rightbackclaw2.render(par7);
        rightbackclaw3.render(par7);
        leftbackleg1.render(par7);
        leftbackleg2.render(par7);
        leftbackleg3.render(par7);
        leftbackfoot.render(par7);
        leftbackclaw1.render(par7);
        leftbackclaw2.render(par7);
        leftbackclaw3.render(par7);
        tail1.render(par7);
        tail2.render(par7);
        tail3.render(par7);
        tail4.render(par7);
        tail5.render(par7);
        GL11.glPopMatrix();
    }
    else
    {
    head.render(par7);
    body.render(par7);
    rightfrontleg1.render(par7);
    rightfrontleg2.render(par7);
    rightfrontfoot.render(par7);
    rightfrontclaw1.render(par7);
    rightfrontclaw2.render(par7);
    rightfrontclaw3.render(par7);
    leftfrontleg1.render(par7);
    leftfrontleg2.render(par7);
    leftfrontfoot.render(par7);
    leftfrontclaw1.render(par7);
    leftfrontclaw2.render(par7);
    leftfrontclaw3.render(par7);
    rightbackleg1.render(par7);
    rightbackleg2.render(par7);
    rightbackleg3.render(par7);
    rightbackfoot.render(par7);
    rightbackclaw1.render(par7);
    rightbackclaw2.render(par7);
    rightbackclaw3.render(par7);
    leftbackleg1.render(par7);
    leftbackleg2.render(par7);
    leftbackleg3.render(par7);
    leftbackfoot.render(par7);
    leftbackclaw1.render(par7);
    leftbackclaw2.render(par7);
    leftbackclaw3.render(par7);
    tail1.render(par7);
    tail2.render(par7);
    tail3.render(par7);
    tail4.render(par7);
    tail5.render(par7);
    jaw.render(par7);
    nose.render(par7);
    tooth1.render(par7);
    tooth2.render(par7);
    tooth3.render(par7);
    tooth4.render(par7);
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
      
      EntityNimatin var5 = (EntityNimatin)par7Entity;

      if (var5.isSitting())
      {
      }
      else
      {
      head.rotateAngleY = par4 / (180F / (float)Math.PI);
      head.rotateAngleX = par5 / (180F / (float)Math.PI);
      nose.rotateAngleX = this.head.rotateAngleX;
      nose.rotateAngleY = this.head.rotateAngleY;
      tooth1.rotateAngleY = this.head.rotateAngleY;
      tooth2.rotateAngleY = this.head.rotateAngleY;
      tooth3.rotateAngleY = this.head.rotateAngleY;
      tooth4.rotateAngleY = this.head.rotateAngleY;
      tooth1.rotateAngleX = this.head.rotateAngleX;
      tooth2.rotateAngleX = this.head.rotateAngleX;
      jaw.rotateAngleY = this.head.rotateAngleY;
      jaw.rotateAngleX = par5 / (80F / (float)Math.PI - (-40.555F / (float)Math.PI));
      tooth3.rotateAngleX = this.jaw.rotateAngleX;
      tooth4.rotateAngleX = this.jaw.rotateAngleX;
      
      tail1.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.1F * par2;
      tail2.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.3F * par2;
      tail3.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
      tail4.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.6F * par2;
      tail5.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.7F * par2;
      
      rightfrontleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2;
      leftfrontleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2;
      rightfrontleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.2F * par2;
      leftfrontleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.2F * par2;
      leftbackleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2;
      rightbackleg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2;
      leftbackleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.0F * par2;
      rightbackleg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.0F * par2;
      leftbackleg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      rightbackleg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      rightfrontfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.2F * par2;
      leftfrontfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.2F * par2;
      leftbackfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      rightbackfoot.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      rightfrontclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.2F * par2;
      leftfrontclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.2F * par2;
      rightfrontclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.2F * par2;
      leftfrontclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.2F * par2;
      rightfrontclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.2F * par2;
      leftfrontclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.2F * par2;
      leftbackclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      rightbackclaw1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      leftbackclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      rightbackclaw2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      leftbackclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      rightbackclaw3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      }
  }
  
  public void setLivingAnimations(EntityLiving par1EntityLiving, float par2, float par3, float par4)
  {
      EntityNimatin var5 = (EntityNimatin)par1EntityLiving;

      if (var5.isSitting())
      {
          this.body.rotateAngleX = -0.5F;
          this.body.rotationPointY = -5;
          
          this.head.rotationPointY = -5;
          this.head.rotationPointZ = -28;
          this.nose.rotationPointY = -5;
          this.nose.rotationPointZ = -29;
          this.jaw.rotationPointY = -5;
          this.jaw.rotationPointZ = -29;
          this.tooth1.rotationPointY = 0;
          this.tooth1.rotationPointZ = -28;
          this.tooth2.rotationPointY = 0;
          this.tooth2.rotationPointZ = -28;
          this.tooth3.rotationPointY = -5;
          this.tooth3.rotationPointZ = -29;
          this.tooth4.rotationPointY = -5;
          this.tooth4.rotationPointZ = -29;
          
          this.rightfrontleg1.rotationPointY = 2;
          this.rightfrontleg1.rotationPointZ = -21;
          this.rightfrontleg2.rotationPointZ = -21;
          this.rightfrontfoot.rotationPointZ = -21;
          this.rightfrontclaw1.rotationPointZ = -20;
          this.rightfrontclaw2.rotationPointZ = -20;
          this.rightfrontclaw3.rotationPointZ = -20;
          this.rightfrontleg1.rotateAngleX = 0;
          this.rightfrontleg2.rotateAngleX = 0;
          this.rightfrontfoot.rotateAngleX = 0F;
          this.rightfrontclaw1.rotateAngleX = 0F;
          this.rightfrontclaw2.rotateAngleX = 0F;
          this.rightfrontclaw3.rotateAngleX = 0F;
          
          this.leftfrontleg1.rotationPointY = 2;
          this.leftfrontleg1.rotationPointZ = -21;
          this.leftfrontleg2.rotationPointZ = -21;
          this.leftfrontfoot.rotationPointZ = -23;
          this.leftfrontclaw1.rotationPointZ = -20;
          this.leftfrontclaw2.rotationPointZ = -20;
          this.leftfrontclaw3.rotationPointZ = -20;
          this.leftfrontleg1.rotateAngleX = 0;
          this.leftfrontleg2.rotateAngleX = 0;
          this.leftfrontfoot.rotateAngleX = 0F;
          this.leftfrontclaw1.rotateAngleX = 0F;
          this.leftfrontclaw2.rotateAngleX = 0F;
          this.leftfrontclaw3.rotateAngleX = 0F;
          
          this.rightbackleg1.rotateAngleX = -1.57F;
          this.rightbackleg2.rotateAngleX = -1.57F;
          this.rightbackleg3.rotateAngleX = -1.57F;
          this.rightbackleg1.rotationPointY = 18;
          this.rightbackleg2.rotationPointY = 18;
          this.rightbackleg2.rotationPointZ = 10;
          this.rightbackleg3.rotationPointY = 18;
          
          this.rightbackfoot.rotateAngleX = -1.57F;
          this.rightbackfoot.rotationPointY = 18;
          this.rightbackclaw1.rotateAngleX = -1.57F;
          this.rightbackclaw2.rotateAngleX = -1.57F;
          this.rightbackclaw3.rotateAngleX = -1.57F;
          this.rightbackclaw1.rotationPointY = 18;
          this.rightbackclaw2.rotationPointY = 18;
          this.rightbackclaw3.rotationPointY = 18;
          
          this.leftbackleg1.rotateAngleX = -1.57F;
          this.leftbackleg2.rotateAngleX = -1.57F;
          this.leftbackleg3.rotateAngleX = -1.57F;
          this.leftbackleg1.rotationPointY = 18;
          this.leftbackleg2.rotationPointY = 18;
          this.leftbackleg2.rotationPointZ = 10;
          this.leftbackleg3.rotationPointY = 18;
          
          this.leftbackfoot.rotateAngleX = -1.57F;
          this.leftbackfoot.rotationPointY = 18;
          this.leftbackclaw1.rotateAngleX = -1.57F;
          this.leftbackclaw2.rotateAngleX = -1.57F;
          this.leftbackclaw3.rotateAngleX = -1.57F;
          this.leftbackclaw1.rotationPointY = 18;
          this.leftbackclaw2.rotationPointY = 18;
          this.leftbackclaw3.rotationPointY = 18;
          
          tail1.setRotationPoint(-1F, 21F, 14F);
          setRotation(tail1, 0F, 0F, 0F);
          tail2.setRotationPoint(-1F, 23F, 13F);
          setRotation(tail2, 0.2617994F, 0F, 0F);
          tail3.setRotationPoint(-1F, 20F, 14F);
          setRotation(tail3, 0.6981317F, 0F, 0F);
          tail4.setRotationPoint(-1F, 20F, 14F);
          setRotation(tail4, 0.6981317F, 0F, 0F);
          tail5.setRotationPoint(-1F, 33F, 22F);
          setRotation(tail5, 1.22173F, 0F, 0F);
          
      }
      else
      {
          head.setRotationPoint(-1F, 0F, -24F);
          setRotation(head, 0F, 0F, 0F);
          jaw.setRotationPoint(-1F, 0F, -24F);
          setRotation(jaw, 0F, 0F, 0F);
          nose.setRotationPoint(-1F, 0F, -24F);
          setRotation(nose, 0F, 0F, 0F);
          tooth1.setRotationPoint(-1F, 5F, -24F);
          setRotation(tooth1, 0F, 0F, 0F);
          tooth2.setRotationPoint(-1F, 5F, -24F);
          setRotation(tooth2, 0F, 0F, 0F);
          tooth3.setRotationPoint(-1F, 0F, -24F);
          setRotation(tooth3, 0F, 0F, 0F);
          tooth4.setRotationPoint(-1F, 0F, -24F);
          setRotation(tooth4, 0F, 0F, 0F);
    	  this.body.rotateAngleX = 0F;
    	  this.body.rotationPointY = -1;
          rightfrontleg1.setRotationPoint(-9F, -1F, -12F);
          setRotation(rightfrontleg1, 0F, 0F, 0F);
          rightfrontleg2.setRotationPoint(-9F, -1F, -12F);
          setRotation(rightfrontleg2, 0F, 0F, 0F);
          rightfrontfoot.setRotationPoint(-9F, 0F, -12F);
          setRotation(rightfrontfoot, 0F, 0F, 0F);
          rightfrontclaw1.setRotationPoint(-9F, -1F, -12F);
          setRotation(rightfrontclaw1, 0F, 0F, 0F);
          rightfrontclaw2.setRotationPoint(-9F, -1F, -12F);
          setRotation(rightfrontclaw2, 0F, 0F, 0F);
          rightfrontclaw3.setRotationPoint(-9F, -1F, -12F);
          setRotation(rightfrontclaw3, 0F, 0F, 0F);
          leftfrontleg1.setRotationPoint(7F, -1F, -12F);
          setRotation(leftfrontleg1, 0F, 0F, 0F);
          leftfrontleg2.setRotationPoint(7F, -1F, -12F);
          setRotation(leftfrontleg2, 0F, 0F, 0F);
          leftfrontfoot.setRotationPoint(7F, 0F, -14F);
          setRotation(leftfrontfoot, 0F, 0F, 0F);
          leftfrontclaw1.setRotationPoint(7F, -1F, -12F);
          setRotation(leftfrontclaw1, 0F, 0F, 0F);
          leftfrontclaw2.setRotationPoint(7F, -1F, -12F);
          setRotation(leftfrontclaw2, 0F, 0F, 0F);
          leftfrontclaw3.setRotationPoint(7F, -1F, -12F);
          setRotation(leftfrontclaw3, 0F, 0F, 0F);
          rightbackleg1.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackleg1, 0F, 0F, 0F);
          rightbackleg2.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackleg2, 0F, 0F, 0F);
          rightbackleg3.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackleg3, 0F, 0F, 0F);
          rightbackfoot.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackfoot, 0F, 0F, 0F);
          rightbackclaw1.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackclaw1, 0F, 0F, 0F);
          rightbackclaw2.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackclaw2, 0F, 0F, 0F);
          rightbackclaw3.setRotationPoint(-9F, -1F, 12F);
          setRotation(rightbackclaw3, 0F, 0F, 0F);
          leftbackleg1.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackleg1, 0F, 0F, 0F);
          leftbackleg2.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackleg2, 0F, 0F, 0F);
          leftbackleg3.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackleg3, 0F, 0F, 0F);
          leftbackfoot.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackfoot, 0F, 0F, 0F);
          leftbackclaw1.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackclaw1, 0F, 0F, 0F);
          leftbackclaw2.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackclaw2, 0F, 0F, 0F);
          leftbackclaw3.setRotationPoint(7F, -1F, 12F);
          setRotation(leftbackclaw3, 0F, 0F, 0F);
          tail1.setRotationPoint(-1F, 0F, 21F);
          setRotation(tail1, -0.4363323F, 0F, 0F);
          tail2.setRotationPoint(-1F, 0F, 21F);
          setRotation(tail2, -0.4363323F, 0F, 0F);
          tail3.setRotationPoint(-1F, 0F, 21F);
          setRotation(tail3, 0.0872665F, 0F, 0F);
          tail4.setRotationPoint(-1F, 0F, 21F);
          setRotation(tail4, 0.0872665F, 0F, 0F);
          tail5.setRotationPoint(-1F, 0F, 21F);
          setRotation(tail5, 0.0872665F, 0F, 0F);
      }
      this.head.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.jaw.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.nose.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.tooth1.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.tooth2.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.tooth3.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.tooth4.rotateAngleZ = var5.getInterestedAngle(par4) + var5.getShakeAngle(par4, 0.0F);
      this.body.rotateAngleZ = var5.getShakeAngle(par4, -0.16F);
      this.tail1.rotateAngleZ = var5.getShakeAngle(par4, -0.2F);
      this.tail2.rotateAngleZ = var5.getShakeAngle(par4, -0.2F);
      this.tail3.rotateAngleZ = var5.getShakeAngle(par4, -0.2F);
      this.tail4.rotateAngleZ = var5.getShakeAngle(par4, -0.2F);
      this.tail5.rotateAngleZ = var5.getShakeAngle(par4, -0.2F);
  }
}
